In [1]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

#array creation
arr_1d=np.array([1,2,3])
print(arr_1d)
print(type(arr_1d))
arr_1d.ndim





[1 2 3]
[1 2 3]
<class 'numpy.ndarray'>


1

In [4]:
#2d array
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)
print(type(arr_2d))
arr_2d.ndim
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr.size)

#print(arr_2d.shape)
#print(arr_2d.type)




[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
3


In [6]:
#ones for column
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)
np.ones(5)
mx_1s.dtype

[[1 2 3]
 [4 5 6]]


NameError: name 'mx_1s' is not defined

In [ ]:
#1's matrix
#mx_1s=np.array(([1,1,1],[1,1,1],[1,1,1]))
#print(mx_1s)

In [ ]:
#ones matrix for rows ans column
#mx_1s=np.ones((3,4))
#print(mx_1s)

In [ ]:
#create zero matrix
#mx_0s=np.zeros((4,6),dtype=bool)
#print(mx_0s)
#mx_0s=np.zeros((4,6),dtype=str)
#print(mx_0s)
#mx_0s=np.zeros((4,6),dtype=float)
#print(mx_0s)